#!/bin/bash
set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==> Installing packages..."
sudo pacman -S --needed - < "$REPO_DIR/packages.txt"

echo "==> Installing AUR packages..."
paru -S --needed - < "$REPO_DIR/packages-aur.txt"

echo "==> Enabling services..."
sudo systemctl enable --now bluetooth iwd
systemctl --user enable --now pipewire wireplumber swayosd-libinput-backend

echo "==> Linking configs..."
for dir in "$REPO_DIR/config"/*/; do
  name=$(basename "$dir")
  dest="$HOME/.config/$name"
  # Remove existing real dir so ln can create a proper symlink
  [ -d "$dest" ] && [ ! -L "$dest" ] && rm -rf "$dest"
  ln -sf "$dir" "$dest"
  # If dest was recreated as a real dir (e.g. Hyprland holding it open),
  # fall back to symlinking individual files inside
  if [ -d "$dest" ] && [ ! -L "$dest" ]; then
    for f in "$dir"*; do
      [ -f "$f" ] && ln -sf "$f" "$dest/$(basename "$f")"
    done
  fi
done
ln -sf "$REPO_DIR/config/starship.toml" "$HOME/.config/starship.toml"

# Remove any autogenerated Hyprland stub so hyprland.lua is used on first start
rm -f "$HOME/.config/hypr/hyprland.conf"

echo "==> Installing wallpaper..."
mkdir -p "$HOME/.local/share/mycachy/wallpapers"
cp "$REPO_DIR/wallpapers/mycachy-wallpaper.png" "$HOME/.local/share/mycachy/wallpapers/mycachy-wallpaper.png"

echo "==> Creating default folders..."
mkdir -p "$HOME/Pictures/Screenshots"
mkdir -p "$HOME/Videos"

echo "==> Installing themes..."
mkdir -p "$HOME/.local/share/mycachy/themes"
for dir in "$REPO_DIR/themes"/*/; do
  name=$(basename "$dir")
  mkdir -p "$HOME/.local/share/mycachy/themes/$name"
  cp "$dir/colors.toml" "$HOME/.local/share/mycachy/themes/$name/colors.toml"
done

echo "==> Installing elephant menus..."
for dir in "$REPO_DIR/config/elephant/install"/*/; do
  name=$(basename "$dir")
  dest="$HOME/.local/share/elephant/install/$name"
  mkdir -p "$dest"
  for f in "$dir"*; do
    [ -f "$f" ] && ln -sf "$f" "$dest/$(basename "$f")"
  done
done

echo "==> Installing bin scripts..."
mkdir -p "$HOME/.local/bin"
for f in "$REPO_DIR/bin/"*; do
  [ -f "$f" ] && ln -sf "$f" "$HOME/.local/bin/$(basename "$f")"
done

echo "==> Applying default theme..."
"$HOME/.local/bin/mycachy-theme-set" catppuccin 2>/dev/null || true

echo "==> Installing Claude Code..."
npm install -g @anthropic-ai/claude-code

echo "==> Setting fish as default shell..."
chsh -s /usr/bin/fish

echo ""
echo "Done. Log out and back in to start the desktop."
