# Catppuccin Mocha

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = #1e1e2e
    path = ~/Pictures/wallpaper
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = #313244
    outer_color = #cba6f7
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = #cdd6f4

    placeholder_text = Enter Password
    check_color = #a6e3a1
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
