general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# On battery: lock after 2.5 minutes
listener {
    timeout = 150
    on-timeout = [ "$(cat /sys/class/power_supply/ACAD/online)" = "0" ] && hyprlock
    on-resume = hyprctl dispatch dpms on
}

# On battery: screen off after 3 minutes
listener {
    timeout = 180
    on-timeout = [ "$(cat /sys/class/power_supply/ACAD/online)" = "0" ] && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# On AC: lock after 15 minutes
listener {
    timeout = 900
    on-timeout = [ "$(cat /sys/class/power_supply/ACAD/online)" = "1" ] && hyprlock
    on-resume = hyprctl dispatch dpms on
}

# On AC: screen off after 30 minutes
listener {
    timeout = 1800
    on-timeout = [ "$(cat /sys/class/power_supply/ACAD/online)" = "1" ] && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
